import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Button from '../components/Button'
import Menu from '../components/Menu'
import { LinkIcon, TrashIcon } from '@heroicons/react/24/solid'
import { useRouter } from 'next/router'
import { useSession } from 'next-auth/react'

const Home: NextPage = () => {
  const router = useRouter()
  const { data: session } = useSession();

  return (
    <div className='container mx-auto'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />

      {/* <Header> */}
      <div className='flex flex-col place-items-center py-32 space-y-3'>
        <h1 className='text-5xl font-bold'>Ayo Mulai Voting</h1>
        <h2 className='text-lg bg-zinc-100 px-3 py-1'>Web Voting No. 1 Di Indonesia</h2>
        <Image src={'/assets/header.svg'} width={274} height={243} alt='header' />
        <div className='space-x-10'>
          <Button
            text='Buat Vote Baru'
            onClick={() => router.push('/vote/create')}
          />
          <Button
            text='Ikutan Vote'
            type='secondary'
            className='text-black'
            onClick={() => router.push('/participant')}
          />
        </div>
      </div>
      {/* </Header> */}

      {/* <Table> */}
      {session && (
        <div>
          <p className='py-5 text-lg font-bold'>Vote yang saya buat</p>
          <table className='table-auto w-full border border-zinc-100'>
            <thead>
              <tr className='border-b border-zinc-100'>
                <th className='p-5 text-left'>No</th>
                <th className='p-5 text-left'>Judul</th>
                <th className='p-5 text-left'>Kandidat</th>
                <th className='p-5 text-left'>Kode</th>
                <th className='p-5 text-left'>Mulai</th>
                <th className='p-5 text-left'>Selesai</th>
                <th className='p-5 text-left'></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className='p-5 text-left'>1</td>
                <td className='p-5 text-left'>Judul Kandidat</td>
                <td className='p-5 text-left'>Kandidat Budi</td>
                <td className='p-5 text-left'>Kode Kandidta</td>
                <td className='p-5 text-left'>Mulai kandidat</td>
                <td className='p-5 text-left'>Selesai Kandidat</td>
                <td className='p-5 text-left'>
                  <a href='#'>
                    <LinkIcon className='w-4 h-4 hover:text-zinc-600' />
                  </a>
                  <a href='#'>
                    <TrashIcon className='w-4 h-4 hover:text-zinc-600' />
                  </a>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      )}

      {/* </Table> */}
    </div>
  )
}

export default Home
